language: python
python:
- '3.6'
stages:
- test
- deploy
jobs:
  include:
  - stage: test
    name: pytest
    install:
    - pip install -r requirements-dev.txt
    script:
    - pytest --cov=nowplaying
  - name: container image
    services:
    - docker
    install:
    - curl -L -O https://github.com/openshift/source-to-image/releases/download/v1.1.14/source-to-image-v1.1.14-874754de-linux-386.tar.gz
    - tar xvf source-to-image-v1.1.14-874754de-linux-386.tar.gz ./s2i
    script:
    - "./s2i build --copy . registry.centos.org/centos/python-36-centos7 radiorabe/nowplaying:${TRAVIS_TAG:-${TRAVIS_COMMIT}}"
