name: Lint and Test

on:
  pull_request:
    branches:
      - main

jobs:
  pre-commit:
    uses: radiorabe/actions/.github/workflows/test-pre-commit.yaml@479996126a091287dc3fd349786f6f8a6dd1b23c # v0.42.0
  test-python-poetry:
    uses: radiorabe/actions/.github/workflows/test-python-poetry.yaml@479996126a091287dc3fd349786f6f8a6dd1b23c # v0.42.0
