name: Release

on:
  pull_request:
  push:
    branches:
      - main
    tags:
      - '*'
jobs:
  release-container:
    uses: radiorabe/actions/.github/workflows/release-container.yaml@f49d301c653f9aa0d99bec7b7f18f2d789e93fa7 # v0.43.4
    with:
      image: 'ghcr.io/radiorabe/nowplaying'
      name: nowplaying
      display-name: RaBe nowplaying daemon.
      tags: minimal rhel9 rabe python nowplaying

  python-poetry:
    uses: radiorabe/actions/.github/workflows/release-python-poetry.yaml@f49d301c653f9aa0d99bec7b7f18f2d789e93fa7 # v0.43.4
    permissions:
      contents: write # Required to push the gh-pages branch for documentation deployment
    secrets:
      RABE_PYPI_TOKEN: ${{ secrets.RABE_PYPI_TOKEN }}
