name: Release

on:
  pull_request:
  push:
    branches:
      - main
    tags:
      - '*'
jobs:
  release-container:
    uses: radiorabe/actions/.github/workflows/release-container.yaml@953c51da7e4c2c681f15c70513cb803c8fa461cc # v0.44.3
    with:
      image: 'ghcr.io/radiorabe/nowplaying'
      name: nowplaying
      display-name: RaBe nowplaying daemon.
      tags: minimal rhel9 rabe python nowplaying

  python-poetry:
    uses: radiorabe/actions/.github/workflows/release-python-poetry.yaml@953c51da7e4c2c681f15c70513cb803c8fa461cc # v0.44.3
    permissions:
      contents: write # Required to push the gh-pages branch for documentation deployment
    secrets:
      RABE_PYPI_TOKEN: ${{ secrets.RABE_PYPI_TOKEN }}
