name: Release

on:
  pull_request:
  push:
    branches: [main]
  release:
    types: [created]

jobs:
  release-container:
    uses: radiorabe/actions/.github/workflows/release-container.yaml@v0.17.1
    with:
      image: 'ghcr.io/radiorabe/nowplaying'
      name: nowplaying
      display-name: RaBe nowplaying daemon.
      tags: minimal rhel9 rabe python nowplaying

  python-poetry:
    uses: radiorabe/actions/.github/workflows/release-python-poetry.yaml@v0.17.1
    secrets:
      RABE_PYPI_TOKEN: ${{ secrets.RABE_PYPI_TOKEN }}
