name: Release

on:
  pull_request:
  push:
    branches:
      - main
    tags:
      - '*'
jobs:
  release-container:
    uses: radiorabe/actions/.github/workflows/release-container.yaml@3f1ee42ffa54794a512d3989c34e3b4514de64cc # v0.43.1
    with:
      image: 'ghcr.io/radiorabe/nowplaying'
      name: nowplaying
      display-name: RaBe nowplaying daemon.
      tags: minimal rhel9 rabe python nowplaying

  python-poetry:
    uses: radiorabe/actions/.github/workflows/release-python-poetry.yaml@3f1ee42ffa54794a512d3989c34e3b4514de64cc # v0.43.1
    permissions:
      contents: write # Required to push the gh-pages branch for documentation deployment
    secrets:
      RABE_PYPI_TOKEN: ${{ secrets.RABE_PYPI_TOKEN }}
